xen-tools: Remove the recommendation for Qemu
After switching to Kirkstone we face the following issue:
ERROR: core-image-thin-initramfs-1.0-r0 do_image_cpio:
The initramfs size 730231(K) exceeds INITRAMFS_MAXSIZE: 131072(K)
The have got a bloated initramfs and the significant part was caused
by Qemu.

As it turned out, the problem is in soft dependency xen-tools on Qemu.
Remove the recommendation for Qemu recently added in meta-virtualization
layer Kirkstone branch by the following commit:
"80047c7 xen, xen-tools: add recommendation for Qemu for non-hvm x86"
in order to not build and install Qemu.

Signed-off-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
---
New, instead of "prod-devel-rcar.yaml: Do not install Qemu into uInitramfs image"
---